basePath: /
definitions:
  dto.PetInsertDto:
    properties:
      adoption_date:
        example: "2008-01-02T15:04:05Z"
        type: string
      birthdate:
        example: "2006-01-02T15:04:05Z"
        type: string
      breed_id:
        example: 0e0b8399-1bf1-4ed5-a2f4-b5789ddf5df0
        type: string
      name:
        example: Thor
        type: string
      size:
        example: medium
        type: string
      user_id:
        example: fa1b8ae8-5351-11ef-8f02-0242ac130003
        type: string
      weight:
        example: 4.1
        type: number
    type: object
host: localhost:3000/api
info:
  contact:
    name: DevHatt
    url: https://github.com/devhatt
  description: Esta página se destina a documentação da API do projeto PetDex Backend
  license:
    name: MIT license
    url: https://github.com/devhatt/pet-dex-backend?tab=MIT-1-ov-file#readme
  title: 'PetDex: Documentação API'
  version: "1.0"
paths:
  /pets/:
    post:
      consumes:
      - application/json
      description: Sends the Pet's registration data via the request body for persistence
        in the database.
      parameters:
      - description: Pet object information for registration
        in: body
        name: petDto
        required: true
        schema:
          $ref: '#/definitions/dto.PetInsertDto'
      produces:
      - application/json
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Create Pet by petDto
      tags:
      - Pet
swagger: "2.0"
