basePath: /
host: localhost:3000/api/swagger
info:
  contact:
    name: DevHatt
    url: https://github.com/devhatt
  description: Essa página se destina a documentação da API
  license:
    name: MIT license
    url: https://github.com/devhatt/pet-dex-backend?tab=MIT-1-ov-file#readme
  title: 'PetDex: Documentação API'
  version: "1.0"
paths: {}
swagger: "2.0"
